name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  MainPipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Caches pip by default (keyed on Python version + requirements)
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      # Fail fast on formatting/lint issues
      - name: Lint
        run: |
          ruff format --check .
          ruff check --output-format=github .

      # Run tests with coverage; pyproject already configures addopts
      - name: Tests
        run: |
          pytest -q

      # Upload coverage/HTML report if you enable it locally (optional)
      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            .coverage
            htmlcov/
          if-no-files-found: ignore
